import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/footer";
import Navbar from "../components/Navbar";
import {Heebo, Inter} from "next/font/google";

const heebo = Heebo({ subsets:["latin"], weight: ["400","700", "900"] });
const inter = Inter({ subsets:["latin"], weight: ["400","700"] });

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
  <Navbar />    
      <div className="mt-5 mb-5"> {children}</div>
  <Footer />
      </body>
    </html>
  );
}
